// TicketContract ABI and address for frontend integration

export const TICKET_CONTRACT_ADDRESS = "0xfB620c721CC55a4f2BFe8E8272aCb6FFEA1b851D";

export const TICKET_CONTRACT_ABI = [
    { "type": "constructor", "inputs": [{ "name": "_eventContractAddress", "type": "address", "internalType": "address" }], "stateMutability": "nonpayable" },
    { "type": "function", "name": "approve", "inputs": [{ "name": "to", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
    { "type": "function", "name": "balanceOf", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
    { "type": "function", "name": "bulkMintTickets", "inputs": [{ "name": "eventId", "type": "uint256", "internalType": "uint256" }, { "name": "quantity", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "uint256[]", "internalType": "uint256[]" }], "stateMutability": "payable" },
    { "type": "function", "name": "buyTicket", "inputs": [{ "name": "ticketId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "payable" },
    { "type": "function", "name": "claimRefund", "inputs": [{ "name": "ticketId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
    { "type": "function", "name": "eventContract", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "contract EventContract" }], "stateMutability": "view" },
    { "type": "function", "name": "eventTickets", "inputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }, { "name": "", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
    { "type": "function", "name": "getApproved", "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
    { "type": "function", "name": "getEventTickets", "inputs": [{ "name": "eventId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "uint256[]", "internalType": "uint256[]" }], "stateMutability": "view" },
    { "type": "function", "name": "getTicketDetails", "inputs": [{ "name": "ticketId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "tuple", "internalType": "struct TicketContract.Ticket", "components": [{ "name": "id", "type": "uint256", "internalType": "uint256" }, { "name": "eventId", "type": "uint256", "internalType": "uint256" }, { "name": "price", "type": "uint256", "internalType": "uint256" }, { "name": "isForSale", "type": "bool", "internalType": "bool" }, { "name": "isRefunded", "type": "bool", "internalType": "bool" }] }], "stateMutability": "view" },
    { "type": "function", "name": "getUserTickets", "inputs": [{ "name": "user", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "uint256[]", "internalType": "uint256[]" }], "stateMutability": "view" },
    { "type": "function", "name": "isApprovedForAll", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }, { "name": "operator", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
    { "type": "function", "name": "listTicketForSale", "inputs": [{ "name": "ticketId", "type": "uint256", "internalType": "uint256" }, { "name": "newPrice", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
    { "type": "function", "name": "mintTicket", "inputs": [{ "name": "eventId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "payable" },
    { "type": "function", "name": "name", "inputs": [], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
    { "type": "function", "name": "owner", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
    { "type": "function", "name": "ownerOf", "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
    { "type": "function", "name": "renounceOwnership", "inputs": [], "outputs": [], "stateMutability": "nonpayable" },
    { "type": "function", "name": "safeTransferFrom", "inputs": [{ "name": "from", "type": "address", "internalType": "address" }, { "name": "to", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
    { "type": "function", "name": "safeTransferFrom", "inputs": [{ "name": "from", "type": "address", "internalType": "address" }, { "name": "to", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }, { "name": "data", "type": "bytes", "internalType": "bytes" }], "outputs": [], "stateMutability": "nonpayable" },
    { "type": "function", "name": "setApprovalForAll", "inputs": [{ "name": "operator", "type": "address", "internalType": "address" }, { "name": "approved", "type": "bool", "internalType": "bool" }], "outputs": [], "stateMutability": "nonpayable" },
    { "type": "function", "name": "supportsInterface", "inputs": [{ "name": "interfaceId", "type": "bytes4", "internalType": "bytes4" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
    { "type": "function", "name": "symbol", "inputs": [], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
    { "type": "function", "name": "tickets", "inputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "id", "type": "uint256", "internalType": "uint256" }, { "name": "eventId", "type": "uint256", "internalType": "uint256" }, { "name": "price", "type": "uint256", "internalType": "uint256" }, { "name": "isForSale", "type": "bool", "internalType": "bool" }, { "name": "isRefunded", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
    { "type": "function", "name": "tokenURI", "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
    { "type": "function", "name": "transferFrom", "inputs": [{ "name": "from", "type": "address", "internalType": "address" }, { "name": "to", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
    { "type": "function", "name": "transferOwnership", "inputs": [{ "name": "newOwner", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
    { "type": "function", "name": "transferTicket", "inputs": [{ "name": "ticketId", "type": "uint256", "internalType": "uint256" }, { "name": "to", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
    { "type": "function", "name": "userTickets", "inputs": [{ "name": "", "type": "address", "internalType": "address" }, { "name": "", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" }
]; 